name: hello
 
on:
  push:
    branches:
      - main

jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: Eco del mensaje
        run: | 
          echo "Hello world"
      - name: Dime la fecha
        run: date
      - run: ls -l