name: Pipeline

on:
  push:
    branches:
        - main

jobs:
    
  Build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout del repositorio.
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 #manda todo el historial de commits
      
      - name: Instalar node.
        uses: actions/setup-node@v4
        with:
          node-version: 20
        
      - name: Instalar las dependencias.
        run: npm install
        #- run: npm ci
      
      - name: Realizar las pruebas y el coverage.
        run: npm run coverage
      
      - name: Hacer la build.
        run: npm run build
          
      - name: Lint
        run: npm run lint

      #sonarcloud

  Deploy:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Checkout del repositorio.
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 #manda todo el historial de commits

      - name: Instalar las dependencias.
        run: npm install

      - name: Instalar Netlify CLI.
        run: npm install -g netlify-cli

      - name: Despliegue.
        uses: jsmrcaga/action-netlify-deploy@v2.0.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.TOKEN_NETLIFY }}
          NETLIFY_DEPLOY_TO_PROD: true
          NETLIFY_SITE_ID: ${{ secrets.ID_NETLIFY }}
          build_directory: 'dist'


  #feedback

