name: Pipeline

on:
  push:
    branches:
        - main

jobs:
    
  Build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout del repositorio.
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 #manda todo el historial de commits
      
      - name: Instalar node.
        uses: actions/setup-node@v4
        with:
          node-version: 18
        

      - name: Instalar las dependencias.
        run: npm install
        #- run: npm ci
      
      - name: Realizar las pruebas.
        run: npm test
      
      #- name: Lint
      #  run: npm run esLint
